### PR TITLE
Update interact.py

### PR DESCRIPTION
**Pull request by santhoshkolloju**
Faster Inference can be achieved by caching the paragraph hidden states and using the past argument in transformer.

### CODE REVIEW

**Comment by martiansideofthemoon** [comment]
Thank you so much for your observation and contribution! I had to fix a couple of things to get this to work on a GPU, and I've also cleaned up parts of the pull request. This change leads to a minor speedup in inference on a GPU (~5-10%, but it will likely be more for longer paragraphs), probably because GPT2 uses a transformer instead of an LSTM and self-attention steps happen in parallel (with respect to sequence length) on a GPU.

I've also verified that this change leads to an identical question generation compared to the baseline model.

A current low hanging fruit is batching the question generation decoding. This is likely to boost inference speed assuming the batch fits on the GPU.

**Comment by martiansideofthemoon** [comment]
I've moved this to #3 to include my commit and closing this for now. It would be great if you could review #3!

**Comment by santhoshkolloju** [comment]
I have tried batching the question generation for a batch. It definitely improves the performance but generated questions are not as good as sequential Processing. It could be because of extra padding tokens we add while batching because of variable length answers .

**Comment by martiansideofthemoon** [comment]
One option (to avoid the padding issues) is to not have `<answer-general>` in the input, and instead keep it as a segment id at the correct part of the paragraph. This will also provide positional information about the answer.

**Pull request closed without merging**
